version: '3'

services:
  web:
    image: 185.92.74.188:5000/helloworld
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
